version: '3.8'

services:
  backend:
    build: ./backend
    image: my-backend-image
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    image: my-frontend-image
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend